services:
  javinizer:
    build: .
    container_name: javinizer
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ${JAVINIZER_DATA_PATH}:/javinizer
      - ${MEDIA_PATH}:/media
    networks:
      - vpn_network
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.javinizer.entrypoints=websecure"
      - "traefik.http.routers.javinizer.rule=Host(`javinizer.blackark.xyz`)"
      - "traefik.http.routers.javinizer.service=javinizer"
      - "traefik.http.routers.javinizer.tls=true"
      - "traefik.http.routers.javinizer.tls.certresolver=letsencrypt"
      - "traefik.http.services.javinizer.loadbalancer.server.port=${CONTAINER_PORT:-8765}"

  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    restart: unless-stopped
    networks:
      - vpn_network
    environment:
      - LOG_LEVEL=${FLARESOLVERR_LOG_LEVEL:-info}
      - LOG_HTML=${FLARESOLVERR_LOG_HTML:-false}
      - CAPTCHA_SOLVER=${FLARESOLVERR_CAPTCHA_SOLVER:-none}
      - TZ=${TZ:-UTC}

networks:
  vpn_network:
    external: true
  proxy:
    external: true
